routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('design.index');
});

Route::get('home', function () {
    return view('home.index');
});

Route::get('test', function() {
	return view ('home.index');
});

Route::resource('clothes', 'ClotheController');


Route::get('/summer', 'SummerController@index')->name('summer.index');

Route::get('/autumn', function(){
	return view('autumn.index');
})->name('autumn.index');


Auth::routes();
Auth::routes();

Route::get('/home', 'HomeController@index');

app/Clothe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clothe extends Model
{
    //
    protected $fillable = [
    'title',
    'description',
    'photo',
    'size',
    'price',
    'quantity',
    ];
}

app/Design.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Design extends Model
{
    protected $fillable = [
    'title',
    'size',
    'price',
    'image',
    'description',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ClotheController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ClotheController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clothes=\App\Clothe::all();
        return view('clothes.index', compact('clothes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $clothes = \App\Clothe::all();
        return view('clothes.create', compact('clothes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        \App\Clothe::create($request->all());
        return redirect()->route('clothes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $clothe = \App\Clothe::find($id);
        return view('clothes.show', compact('clothe'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
         $clothe = \App\Clothe::find($id);

    $clothes = \App\Clothe::all(); 
    $selectClothes = array();
    foreach ($clothes as $clothe) {
    $selectMenus[$clothe->id] = $clothe->name;
    }

    return view("clothes.create", compact("clothe", "selectClothe"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
         $clothe = \App\Clothe::find($id);
        $clothe->update($request->all());

        return redirect()->route('clothes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
          
        \App\Clothe::find($id)->delete();
       

        return redirect()->route('clothes.index');
    
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DesignController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DesignController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        return view('design.index', compact('design'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SummerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SummerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('summer.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/autumn/index.blade.php
@extends('main')
@section('content')
labas
@endsection

resources/views/clothes/create.blade.php
@extends('main')
@section('content')

@if(isset($clothe))
{!!Form::model($clothe, ['route' => ['clothes.update', $clothe->id], 'method'=>'PUT'] )!!}
@else
{!!Form::open(['route' => 'clothes.store', 'method'=>'POST'] )!!}
@endif

{{csrf_field()}}

{!! Form::label('title', 'Title :')!!}
{!! Form::text('title', null, ['class'=>'form-control'] )!!}

{!! Form::label('description', 'Description:')!!}
{!! Form::text('description', null,  ['class'=>'form-control'] )!!}

{!! Form::label('photo', 'Photo :')!!}
{!! Form::text('photo', null, ['class'=>'form-control'] )!!}

{!! Form::label('size', 'Size:')!!}
{!! Form::text('size', null, ['class'=>'form-control'] )!!}


{!! Form::label('price', 'Price :')!!}
{!! Form::number('price', null, ['class'=>'form-control'] )!!}

{!! Form::label('quantity', 'Quantity :')!!}
{!! Form::number('quantity', null, ['class'=>'form-control'] )!!}





{!!Form::submit('Submit')!!}
{!! Form::close() !!}



@if(isset($clothe))

	{{ Form::open(['route' => ['clothes.destroy', $clothe->id], "method" => "POST"]) }}
		<input type="hidden" name="_method" value="DELETE">

		{{ csrf_field() }}

	
		{!! Form::submit('Detele', ['class' => 'btn btn-danger']); !!}
	{!! Form::close() !!}

@endif

@endsection

resources/views/clothes/index.blade.php
@extends('main')
@section('content')

<div class="container">
	<div class="row">
				@foreach($clothes as $clothe)
		<div class="col-md-3 ">
			<ul>

				<li>
					<h3>{{ $clothe->title }}</h3>
					<small>{{ $clothe->price }}</small>

					<p>{{ mb_strimwidth($clothe->description, 0 , 50, '...') }}</p>

					<p>{{ $clothe->photo }}</p>

					<a href="{{ route('clothes.edit', $clothe->id)}}" class="btn btn-info">EDIT</a>
					<a href="{{ route('clothes.create')}}" class="btn btn-info">Add Clothes </a>
					<a href=" {{ route('clothes.show', $clothe->id) }} " class="btn btn-primary">READ MORE</a>
				</li>
			</ul>
		</div>

		@endforeach
	</div>
</div>
@endsection

resources/views/clothes/show.blade.php
@include('main')
@section('content')
<div class="well" class="col-md-4">
	<h3>{{ $clothe->title }} </h3>
	<p>{{ $clothe->photo }}</p>
	<p> {{ $clothe->description }} </p>
	<small>{{ $clothe->price }}</small>
	<small>{{ $clothe->netto_price }}</small>
	<p>{{ $clothe->quantity }}</p>
	

	 <h1>labas</h1>
</div>
@endsection

resources/views/design/index.blade.php
@extends('main')
@section('content')

<!DOCTYPE html>
<html lang="en">
<head>
  <title>VK Design 3WA</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
</head>
<body>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="http://www.ibcworldnews.com/gallery/wp-content/uploads/2016/01/047ba164-8693-4028-8815-c419f090fa14.jpg" alt="Image" width="300" height="300">
        <div class="carousel-caption">
          <h3>Clothing for special women!</h3>
          <p>Get exclusive design today!</p>
        </div>      
      </div>

      <div class="item">
        <img src="http://kingofwallpapers.com/fashion-images/fashion-images-020.jpg" alt="Image" width="300" height="300">
      </div>

      <div class="item">
        <img src="https://s-media-cache-ak0.pinimg.com/originals/21/4d/de/214ddee5f850843957e1281abee0ee2a.jpg?text=New summer 2017 Collection" alt="Image" width="300" height="300">
        <div class="carousel-caption">
          <h3>More Sell $</h3>
          <p>Lorem ipsum...</p>
        </div>      
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
  
<div class="container text-center">    
  <h3>What We Do</h3><br>
  <div class="row">
    <div class="col-sm-4">
      <img src="http://www.tucsonmodelgroup.com/wp-content/uploads/2016/05/tucson-model-agency.jpg?text=Collection" class="img-responsive" style="width:100%" alt="Image">
      <a href="{{ route('summer.index')}}">Summer collection</a>
    </div>
    <div class="col-sm-4"> 
      <img src="http://www.uricom.nl/wp-content/uploads/spring-fascion3-1.jpg?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <a href="{{ route('autumn.index')}}">Autumn 2017 Collection</a>    
    </div>
    <div class="col-sm-4">
      <div class="well">
       <p>Some text..</p>
      </div>
      <div class="well">
       <p>Some text..</p>
      </div>
    </div>
  </div>
</div><br>


<div class="container">
	<div class="header clearfix">
		
		<h3 class="text-muted">

		</h3>
	</div>
</div>
<div class="jumbotron container">
	<p class="lead"></p>

	<img class="container image-responsive" src="http://www.nandos.com/sites/all/themes/nandos/images/restaurants/restaurant-carousel-1.jpg">
</div>


  

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home/index.blade.php
@extends('main')
<div class="container">
@yield('content')
</div>
@endsection

resources/views/layout/footer.blade.php
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6">
        <div class="logofooter"> Logo</div>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</p>
        <p><i class="fa fa-map-pin"></i> Gedimino ave. 32-3 Vilnius Lithuania</p>
        <p><i class="fa fa-phone"></i> Phone (Lithuania) : +37060660012</p>
        <p><i class="fa fa-envelope"></i> E-mail : info@design.lt</p>
      
       </div>
          <div class="col-md-6 col-sm-6">
            <h5 class="white-text">Nuorodos</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="{{ URL::route('clothes.index') }}">Clothes</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">About us</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!"></a></li>
            </ul>
            </div>
        
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        © 2016 Design Company
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </div>
</div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{{asset('js/cart.js')}}"></script>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js"></script>

</body>
</html>

resources/views/layout/header.blade.php
<!DOCTYPE html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}"></link>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">VK Design </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="{{ URL::route('clothes.index') }}">Clothes</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ URL::route('login') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>

        <li><a href="{{ URL::route('register') }}"><span class="glyphicon glyphicon-log-in"></span>Register</a></li>
      </ul>
    </div>
  </div>
</nav>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/main.blade.php
@include("layout.header")
     
<div class="container">
@yield('content')
</div>

 @include("layout.footer")

resources/views/summer/index.blade.php
@extends('main')
@section('content')

<h2 class="w3-center">Manual Slideshow</h2>

<div class="w3-content w3-display-container">
  <img class="mySlides" src="img_fjords.jpg" style="width:100%">
  <img class="mySlides" src="img_lights.jpg" style="width:100%">
  <img class="mySlides" src="img_mountains.jpg" style="width:100%">
  <img class="mySlides" src="img_forest.jpg" style="width:100%">

  <a class="w3-btn-floating w3-display-left" onclick="plusDivs(-1)">&#10094;</a>
  <a class="w3-btn-floating w3-display-right" onclick="plusDivs(1)">&#10095;</a>
</div>

<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";  
  }
  x[slideIndex-1].style.display = "block";  
}
</script>
@endsection